<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>GameNet.Desktop</RootNamespace>
    <AssemblyName>GameNet.Manager.Desktop</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UICulture>en-US</UICulture>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\GameNet.Shared.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Resources\Styles\*.xaml" Generator="MSBuild:Compile"/>
  </ItemGroup>

</Project>
